Fix redo undo shortcut
CS2103JAN2017-W14-B3/main pull request #241
Opened 2017-04-07 08:08 UTC by Fyelight

Closes #234 
by raising success message when no exception is thrown in  mainwindow

2017-04-07 08:10 UTC, jinshunlee requested changes

2017-04-07 08:10 UTC, jinshunlee commented on src/main/java/seedu/doit/ui/MainWindow.java
>              @Override
maybe can change method name handleKeyEvent? also add some header comments here

2017-04-07 10:29 UTC, Fyelight commented
@yexiexie  Add the comments since u did most of it.
I not really sure about the set accelerator really and why it is name that way.
Maybe you can tell us

2017-04-07 10:30 UTC, Fyelight commented
@yexiexie  also add in your collate too.

2017-04-07 16:53 UTC, yexiexie commented
method name setAccelerator() was there for help shortcut F1 linked to menu item. Now that we added some key events, method name can change to keyEvents to be more meaningful.

2017-04-09 06:12 UTC, jinshunlee approved these changes

2017-04-09 06:12 UTC, merged